# Generated by Django 3.0.1 on 2020-01-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_date', models.DateField(default=datetime.datetime.today)),
                ('from_to', models.DateField(default=datetime.datetime.today)),
                ('applicable', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
